#remote_theme: "mmistakes/so-simple-theme"
locale: en-US
github_username: serea
logo: "/images/logo.png"
baseurl: "/"
date_format: "%Y-%m-%d"
read_time: true
words_per_minute: 200
mathjax:  true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: flase# true (default), false

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /
markdown: kramdown
feed:
  path: atom.xml

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

plugins:
#  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-feed
  - jekyll-paginate

# paginate: 10
# paginate_path: /page:num/

# Collections
# collections:
#   cv:
#     output: true
#     permalink: /:cv/

# Front Matter Defaults
defaults:
  - scope:
      path: "index"
      type: 
    values:
      layout: "collections"
      share: true

# Site Author
author:
  name: Suliya
  picture: "/images/serea.jpg"
  email: suliya at iie dot ac dot cn
  twitter:
  links:
    - title:
      url: serea.github.io
      icon:

# Footer Links
footer_links:
  - title: Github
    url: https://github.com/serea
    icon: fab fa-githb-square

copyright: "This site is made by Suliya."